# Generated by Django 5.1.4 on 2025-07-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingsystemmappingrecord',
            name='project',
        ),
        migrations.AddField(
            model_name='historicalusercredentialssetup',
            name='project_joined_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usercredentialssetup',
            name='project_joined_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
