# Generated by Django 5.1.4 on 2025-07-29 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0003_remove_billingsystemmappingrecord_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingsystemmappingrecord',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_project_set', to='setups.projects'),
        ),
    ]
