# Generated by Django 5.1.4 on 2025-07-29 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0004_billingsystemmappingrecord_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingsystemmappingrecord',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_project_set', to='setups.projects'),
        ),
    ]
