# Generated by Django 5.1.4 on 2025-07-29 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0005_alter_billingsystemmappingrecord_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingsystemmappingrecord',
            name='selected_bin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
