# Generated by Django 5.1.4 on 2025-07-30 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0006_billingsystemmappingrecord_selected_bin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingsystemmappingrecord',
            name='selected_bin',
        ),
        migrations.AlterField(
            model_name='billingsystemmappingrecord',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_project_set', to='setups.projects'),
        ),
    ]
