# Generated by Django 5.1.4 on 2025-07-30 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0013_remove_billingsystemmappingrecord_selected_bin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprojects',
            name='billing_system_mapping',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='setups.billingsystemmappingrecord'),
        ),
        migrations.AddField(
            model_name='projects',
            name='billing_system_mapping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_projects', to='setups.billingsystemmappingrecord'),
        ),
        migrations.AlterField(
            model_name='billingsystemmappingrecord',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_project_set', to='setups.projects'),
        ),
    ]
