# Generated by Django 5.1.4 on 2025-07-30 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0014_historicalprojects_billing_system_mapping_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalprojects',
            name='billing_system_mapping',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='billing_system_mapping',
        ),
        migrations.AddField(
            model_name='billingsystemmappingrecord',
            name='selected_bin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='billingsystemmappingrecord',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_project_set', to='setups.projects'),
        ),
    ]
