# Generated by Django 5.1.4 on 2025-08-01 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0015_remove_historicalprojects_billing_system_mapping_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingsystemmappingrecord',
            name='project',
        ),
        migrations.AddField(
            model_name='billingsystemmappingrecord',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='billing_systems', to='setups.projects'),
        ),
    ]
