# Generated by Django 5.1.4 on 2025-08-04 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0017_remove_billingsystemmappingrecord_projects_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingsystemmappingrecord',
            name='project',
        ),
        migrations.AddField(
            model_name='billingsystemmappingrecord',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='billing_systems', to='setups.projects'),
        ),
    ]
