# Generated by Django 5.1.4 on 2025-08-05 07:31

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0019_remove_billingsystemmappingrecord_projects_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalroles',
            name='screens',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('admin', 'Admin'), ('roles', 'Roles'), ('departments', 'Departments'), ('clients', 'Clients'), ('projects', 'Projects'), ('organizations', 'Organizations'), ('stake', 'Stake'), ('apps', 'Apps'), ('upload', 'Upload'), ('zero-upload', 'Zero-Upload'), ('billing-system', 'Billing-System'), ('allocation-ar', 'Allocation-Ar'), ('allocation-denials', 'Allocation-Denials'), ('allocation-ect', 'Allocation-Ect'), ('allocation-corresponding', 'Allocation-Corresponding'), ('executive-ar', 'Executive-Ar'), ('executive-denials', 'Executive-Denials'), ('executive-ect', 'Executive-Ect'), ('executive-corresponding', 'Executive-Corresponding'), ('review-ar', 'Review-Ar'), ('review-coding', 'Review-Coding'), ('review-payments', 'Review-Payments'), ('review-corresponding', 'Review-Corresponding'), ('review-billing', 'Review-Billing'), ('review-credential', 'Review-Credential'), ('organization-rules', 'Organization-Rules'), ('ops-rules', 'Ops-Rules'), ('sop-rules', 'Sop-Rules'), ('view-rules', 'View-Rules'), ('approvals', 'Approvals'), ('holdq', 'HoldQ'), ('create-codes', 'Create-Codes'), ('view-sop-rules', 'View-Sop-Rules'), ('custom-bins', 'Custom-Bins'), ('user-allocation-bins-records', 'User-Allocation-Bins-Records'), ('flow-setup', 'Flow-setup'), ('view-flow-charts', 'View-flows')], max_length=498),
        ),
        migrations.AlterField(
            model_name='roles',
            name='screens',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('admin', 'Admin'), ('roles', 'Roles'), ('departments', 'Departments'), ('clients', 'Clients'), ('projects', 'Projects'), ('organizations', 'Organizations'), ('stake', 'Stake'), ('apps', 'Apps'), ('upload', 'Upload'), ('zero-upload', 'Zero-Upload'), ('billing-system', 'Billing-System'), ('allocation-ar', 'Allocation-Ar'), ('allocation-denials', 'Allocation-Denials'), ('allocation-ect', 'Allocation-Ect'), ('allocation-corresponding', 'Allocation-Corresponding'), ('executive-ar', 'Executive-Ar'), ('executive-denials', 'Executive-Denials'), ('executive-ect', 'Executive-Ect'), ('executive-corresponding', 'Executive-Corresponding'), ('review-ar', 'Review-Ar'), ('review-coding', 'Review-Coding'), ('review-payments', 'Review-Payments'), ('review-corresponding', 'Review-Corresponding'), ('review-billing', 'Review-Billing'), ('review-credential', 'Review-Credential'), ('organization-rules', 'Organization-Rules'), ('ops-rules', 'Ops-Rules'), ('sop-rules', 'Sop-Rules'), ('view-rules', 'View-Rules'), ('approvals', 'Approvals'), ('holdq', 'HoldQ'), ('create-codes', 'Create-Codes'), ('view-sop-rules', 'View-Sop-Rules'), ('custom-bins', 'Custom-Bins'), ('user-allocation-bins-records', 'User-Allocation-Bins-Records'), ('flow-setup', 'Flow-setup'), ('view-flow-charts', 'View-flows')], max_length=498),
        ),
    ]
