# Generated by Django 5.1.4 on 2025-08-07 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0021_alter_historicalroles_screens_alter_roles_screens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingsystemmappingrecord',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_project_set', to='setups.projects'),
        ),
    ]
