# Generated by Django 5.1.4 on 2025-08-09 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0022_alter_billingsystemmappingrecord_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingsystemmappingrecord',
            name='ar_record_cpt_level',
            field=models.BooleanField(default=False, help_text='Enable CPT level AR records'),
        ),
    ]
