# Generated by Django 5.1.4 on 2025-08-09 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0023_billingsystemmappingrecord_ar_record_cpt_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingsystemmappingrecord',
            name='ar_record_cpt_level',
        ),
    ]
