# Generated by Django 5.1.4 on 2025-08-09 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0024_remove_billingsystemmappingrecord_ar_record_cpt_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingsystemmappingrecord',
            name='is_ar_record_cpt_level',
            field=models.BooleanField(default=False, help_text='Enable AR record CPT level processing'),
        ),
    ]
