# Generated by Django 5.1.4 on 2025-08-09 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0025_billingsystemmappingrecord_is_ar_record_cpt_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingsystemmappingrecord',
            name='is_ar_record_cpt_level',
        ),
    ]
