# Generated by Django 5.1.4 on 2025-08-09 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0026_remove_billingsystemmappingrecord_is_ar_record_cpt_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingsystemmappingrecord',
            name='is_cpt_level_ar',
            field=models.BooleanField(default=False, help_text='Enable when AR records are at CPT/procedure code level'),
        ),
    ]
