# Generated by Django 5.1.4 on 2025-08-09 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0027_billingsystemmappingrecord_is_cpt_level_ar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingsystemmappingrecord',
            name='is_cpt_level_ar',
        ),
    ]
