# Generated by Django 5.1.4 on 2025-08-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0028_remove_billingsystemmappingrecord_is_cpt_level_ar'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingsystemmappingrecord',
            name='is_cpt_level',
            field=models.BooleanField(default=False, help_text='When enabled, records with same MRN but different procedure codes are grouped together'),
        ),
    ]
