# Generated by Django 5.1.4 on 2025-08-09 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0029_billingsystemmappingrecord_is_cpt_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingsystemmappingrecord',
            name='is_cpt_level',
        ),
    ]
