# Generated by Django 5.1.4 on 2025-08-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0030_remove_billingsystemmappingrecord_is_cpt_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingsystemmappingrecord',
            name='is_cpt_level',
            field=models.BooleanField(default=False),
        ),
    ]
