# Generated by Django 5.1.4 on 2025-08-09 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0032_remove_billingsystemmappingrecord_is_cpt_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingsystemmappingrecord',
            name='is_ar_record_cpt_level',
        ),
    ]
