# Generated by Django 5.1.4 on 2025-08-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0033_remove_billingsystemmappingrecord_is_ar_record_cpt_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingsystemmappingrecord',
            name='ar_record_cpt_level',
            field=models.BooleanField(default=False, help_text='Enable CPT level AR records'),
        ),
    ]
