# Generated by Django 5.1.4 on 2025-08-14 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0036_billingsystemmappingrecord_is_cpt_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_name', models.CharField(max_length=255)),
                ('phone_no', models.CharField(max_length=20)),
                ('extension', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('open_close_time', models.CharField(blank=True, max_length=100, null=True)),
                ('prefix', models.CharField(blank=True, max_length=10, null=True)),
                ('claim_address', models.TextField(blank=True, null=True)),
                ('appeal_address', models.TextField(blank=True, null=True)),
                ('claim_tfl_days', models.PositiveIntegerField(blank=True, help_text='Claim Time Frame Limit in days', null=True)),
                ('appeal_tfl_days', models.PositiveIntegerField(blank=True, help_text='Appeal Time Frame Limit in days', null=True)),
                ('web_page_address', models.URLField(blank=True, max_length=500, null=True)),
                ('group_username', models.CharField(blank=True, max_length=100, null=True)),
                ('group_password', models.CharField(blank=True, max_length=100, null=True)),
                ('individual_username', models.CharField(blank=True, max_length=100, null=True)),
                ('individual_password', models.CharField(blank=True, max_length=100, null=True)),
                ('password_expiry_duration', models.CharField(blank=True, max_length=50, null=True)),
                ('project', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Insurance',
                'verbose_name_plural': 'Insurance Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
