# Generated by Django 5.1.4 on 2025-08-21 12:35

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0038_alter_historicalroles_screens_alter_roles_screens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalroles',
            name='screens',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Roles', 'Roles'), ('Admin', 'Admin'), ('Departments', 'Departments'), ('Projects', 'Projects'), ('Clients', 'Clients'), ('Organizations', 'Organizations'), ('Stake', 'Stake'), ('Apps', 'Apps'), ('Upload', 'Upload'), ('Zero-Upload', 'Zero-Upload'), ('Billing-System', 'Billing-System'), ('Allocation-Ar', 'Allocation-Ar'), ('Allocation-Denials', 'Allocation-Denials'), ('Allocation-Ect', 'Allocation-Ect'), ('Allocation-Corresponding', 'Allocation-Corresponding'), ('Executive-Ar', 'Executive-Ar'), ('Executive-Denials', 'Executive-Denials'), ('Executive-Ect', 'Executive-Ect'), ('Executive-Corresponding', 'Executive-Corresponding'), ('Review-Ar', 'Review-Ar'), ('Review-Coding', 'Review-Coding'), ('Review-Payments', 'Review-Payments'), ('Review-Corresponding', 'Review-Corresponding'), ('Review-Billing', 'Review-Billing'), ('Review-Credential', 'Review-Credential'), ('Organization-Rules', 'Organization-Rules'), ('Ops-Rules', 'Ops-Rules'), ('Sop-Rules', 'Sop-Rules'), ('View-Rules', 'View-Rules'), ('Approvals', 'Approvals'), ('HoldQ', 'HoldQ'), ('Create-Codes', 'Create-Codes'), ('View-Sop-Rules', 'View-Sop-Rules'), ('Custom-Bins', 'Custom-Bins'), ('User-Allocation-Bins-Records', 'User-Allocation-Bins-Records'), ('Insurance-Information', 'Insurance Information'), ('Flow-Setup', 'Flow Setup'), ('View-Flows', 'View Flows'), ('Settings', 'Settings')], max_length=523),
        ),
        migrations.AlterField(
            model_name='roles',
            name='screens',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Roles', 'Roles'), ('Admin', 'Admin'), ('Departments', 'Departments'), ('Projects', 'Projects'), ('Clients', 'Clients'), ('Organizations', 'Organizations'), ('Stake', 'Stake'), ('Apps', 'Apps'), ('Upload', 'Upload'), ('Zero-Upload', 'Zero-Upload'), ('Billing-System', 'Billing-System'), ('Allocation-Ar', 'Allocation-Ar'), ('Allocation-Denials', 'Allocation-Denials'), ('Allocation-Ect', 'Allocation-Ect'), ('Allocation-Corresponding', 'Allocation-Corresponding'), ('Executive-Ar', 'Executive-Ar'), ('Executive-Denials', 'Executive-Denials'), ('Executive-Ect', 'Executive-Ect'), ('Executive-Corresponding', 'Executive-Corresponding'), ('Review-Ar', 'Review-Ar'), ('Review-Coding', 'Review-Coding'), ('Review-Payments', 'Review-Payments'), ('Review-Corresponding', 'Review-Corresponding'), ('Review-Billing', 'Review-Billing'), ('Review-Credential', 'Review-Credential'), ('Organization-Rules', 'Organization-Rules'), ('Ops-Rules', 'Ops-Rules'), ('Sop-Rules', 'Sop-Rules'), ('View-Rules', 'View-Rules'), ('Approvals', 'Approvals'), ('HoldQ', 'HoldQ'), ('Create-Codes', 'Create-Codes'), ('View-Sop-Rules', 'View-Sop-Rules'), ('Custom-Bins', 'Custom-Bins'), ('User-Allocation-Bins-Records', 'User-Allocation-Bins-Records'), ('Insurance-Information', 'Insurance Information'), ('Flow-Setup', 'Flow Setup'), ('View-Flows', 'View Flows'), ('Settings', 'Settings')], max_length=523),
        ),
    ]
