# Generated by Django 5.1.4 on 2025-07-29 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_credentialsform_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credentialsform',
            name='projects',
        ),
    ]
