# Generated by Django 5.1.4 on 2025-08-01 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_remove_credentialsform_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecords',
            name='hold',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
