# Generated by Django 5.1.4 on 2025-08-06 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_patientrecords_hold'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrecordsuploadlogs',
            name='failed_records_data',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='historicalrecordsuploadlogs',
            name='new_records_data',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='historicalrecordsuploadlogs',
            name='updated_records_data',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='recordsuploadlogs',
            name='failed_records_data',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='recordsuploadlogs',
            name='new_records_data',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='recordsuploadlogs',
            name='updated_records_data',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
