# Generated by Django 5.1.4 on 2025-08-06 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_historicalrecordsuploadlogs_failed_records_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalrecordsuploadlogs',
            name='failed_records_data',
        ),
        migrations.RemoveField(
            model_name='historicalrecordsuploadlogs',
            name='new_records_data',
        ),
        migrations.RemoveField(
            model_name='historicalrecordsuploadlogs',
            name='updated_records_data',
        ),
        migrations.RemoveField(
            model_name='recordsuploadlogs',
            name='failed_records_data',
        ),
        migrations.RemoveField(
            model_name='recordsuploadlogs',
            name='new_records_data',
        ),
        migrations.RemoveField(
            model_name='recordsuploadlogs',
            name='updated_records_data',
        ),
    ]
