# Generated by Django 5.1.4 on 2025-08-06 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_remove_historicalrecordsuploadlogs_failed_records_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrecordsuploadlogs',
            name='failed_records_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalrecordsuploadlogs',
            name='failed_records_data',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='historicalrecordsuploadlogs',
            name='upload_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='historicalrecordsuploadlogs',
            name='upload_status',
            field=models.CharField(choices=[('processing', 'Processing'), ('success', 'Success'), ('partial', 'Partial Success'), ('failed', 'Failed')], default='processing', max_length=50),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='csv_row_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='record_status',
            field=models.CharField(choices=[('new', 'New'), ('updated', 'Updated'), ('failed', 'Failed')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='upload_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_records', to='records.recordsuploadlogs'),
        ),
        migrations.AddField(
            model_name='recordsuploadlogs',
            name='failed_records_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recordsuploadlogs',
            name='failed_records_data',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='recordsuploadlogs',
            name='upload_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='recordsuploadlogs',
            name='upload_status',
            field=models.CharField(choices=[('processing', 'Processing'), ('success', 'Success'), ('partial', 'Partial Success'), ('failed', 'Failed')], default='processing', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalrecordsuploadlogs',
            name='new_records_uploaded_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historicalrecordsuploadlogs',
            name='updated_records_uploaded_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recordsuploadlogs',
            name='new_records_uploaded_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recordsuploadlogs',
            name='updated_records_uploaded_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='FailedUploadRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_row_number', models.IntegerField()),
                ('raw_data', models.JSONField()),
                ('failure_reason', models.TextField()),
                ('error_details', models.TextField(blank=True)),
                ('field_errors', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upload_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failed_upload_records', to='records.recordsuploadlogs')),
            ],
        ),
    ]
