# Generated by Django 5.1.4 on 2025-08-06 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_historicalrecordsuploadlogs_failed_records_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalrecordsuploadlogs',
            name='failed_records_count',
        ),
        migrations.RemoveField(
            model_name='historicalrecordsuploadlogs',
            name='failed_records_data',
        ),
        migrations.RemoveField(
            model_name='historicalrecordsuploadlogs',
            name='upload_metadata',
        ),
        migrations.RemoveField(
            model_name='historicalrecordsuploadlogs',
            name='upload_status',
        ),
        migrations.RemoveField(
            model_name='patientrecord',
            name='csv_row_number',
        ),
        migrations.RemoveField(
            model_name='patientrecord',
            name='record_status',
        ),
        migrations.RemoveField(
            model_name='patientrecord',
            name='upload_log',
        ),
        migrations.RemoveField(
            model_name='recordsuploadlogs',
            name='failed_records_count',
        ),
        migrations.RemoveField(
            model_name='recordsuploadlogs',
            name='failed_records_data',
        ),
        migrations.RemoveField(
            model_name='recordsuploadlogs',
            name='upload_metadata',
        ),
        migrations.RemoveField(
            model_name='recordsuploadlogs',
            name='upload_status',
        ),
        migrations.AlterField(
            model_name='historicalrecordsuploadlogs',
            name='new_records_uploaded_count',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='historicalrecordsuploadlogs',
            name='updated_records_uploaded_count',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='recordsuploadlogs',
            name='new_records_uploaded_count',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='recordsuploadlogs',
            name='updated_records_uploaded_count',
            field=models.IntegerField(blank=True),
        ),
        migrations.DeleteModel(
            name='FailedUploadRecords',
        ),
    ]
