# Generated by Django 5.1.4 on 2025-08-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0010_historicalrecordsuploadlogs_failed_records_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalrecordsuploadlogs',
            name='failed_records_count',
        ),
        migrations.RemoveField(
            model_name='historicalrecordsuploadlogs',
            name='failed_records_data',
        ),
        migrations.RemoveField(
            model_name='historicalrecordsuploadlogs',
            name='organization_id',
        ),
        migrations.RemoveField(
            model_name='historicalrecordsuploadlogs',
            name='project_id',
        ),
        migrations.RemoveField(
            model_name='historicalrecordsuploadlogs',
            name='upload_session_id',
        ),
        migrations.RemoveField(
            model_name='recordsuploadlogs',
            name='failed_records_count',
        ),
        migrations.RemoveField(
            model_name='recordsuploadlogs',
            name='failed_records_data',
        ),
        migrations.RemoveField(
            model_name='recordsuploadlogs',
            name='organization_id',
        ),
        migrations.RemoveField(
            model_name='recordsuploadlogs',
            name='project_id',
        ),
        migrations.RemoveField(
            model_name='recordsuploadlogs',
            name='upload_session_id',
        ),
        migrations.AlterField(
            model_name='historicalrecordsuploadlogs',
            name='new_records_uploaded_count',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='historicalrecordsuploadlogs',
            name='updated_records_uploaded_count',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='recordsuploadlogs',
            name='new_records_uploaded_count',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='recordsuploadlogs',
            name='updated_records_uploaded_count',
            field=models.IntegerField(blank=True),
        ),
    ]
