# Generated by Django 5.1.4 on 2025-08-06 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0011_remove_historicalrecordsuploadlogs_failed_records_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrecordsuploadlogs',
            name='failed_records_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='historicalrecordsuploadlogs',
            name='failed_records_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='historicalrecordsuploadlogs',
            name='organization_id',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='historicalrecordsuploadlogs',
            name='project_id',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='historicalrecordsuploadlogs',
            name='upload_session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recordsuploadlogs',
            name='failed_records_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='recordsuploadlogs',
            name='failed_records_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='recordsuploadlogs',
            name='organization_id',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='recordsuploadlogs',
            name='project_id',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='recordsuploadlogs',
            name='upload_session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalrecordsuploadlogs',
            name='new_records_uploaded_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='historicalrecordsuploadlogs',
            name='updated_records_uploaded_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='recordsuploadlogs',
            name='new_records_uploaded_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='recordsuploadlogs',
            name='updated_records_uploaded_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
