# Generated by Django 5.1.4 on 2025-08-06 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0012_historicalrecordsuploadlogs_failed_records_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecords',
            name='upload_session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
