# Generated by Django 5.1.4 on 2025-08-06 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0013_patientrecords_upload_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientrecords',
            name='upload_session_id',
        ),
    ]
