# Generated by Django 5.1.4 on 2025-08-06 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0014_remove_patientrecords_upload_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecord',
            name='upload_session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='RecordUploadTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('NEW', 'New Record'), ('UPDATED', 'Updated Record'), ('FAILED', 'Failed Record')], max_length=10)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('row_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='records.patientrecords')),
                ('upload_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_records', to='records.recordsuploadlogs')),
            ],
            options={
                'db_table': 'record_upload_tracking',
                'indexes': [models.Index(fields=['upload_log', 'action_type'], name='record_uplo_upload__f8a4e2_idx')],
            },
        ),
    ]
