# Generated by Django 5.1.4 on 2025-08-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0017_remove_patientrecords_is_grouped_cpt_record_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecords',
            name='upload_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
