# Generated by Django 5.1.4 on 2025-08-09 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0019_patientrecords_cpt_procedures_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientrecords',
            name='cpt_procedures',
        ),
        migrations.RemoveField(
            model_name='patientrecords',
            name='is_cpt_grouped',
        ),
        migrations.RemoveField(
            model_name='patientrecords',
            name='procedure_count_total',
        ),
    ]
