# Generated by Django 5.1.4 on 2025-08-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0020_remove_patientrecords_cpt_procedures_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecords',
            name='is_grouped_cpt_record',
            field=models.BooleanField(default=False, help_text='Indicates if this is a grouped CPT record'),
        ),
        migrations.AddField(
            model_name='patientrecords',
            name='original_procedure_code',
            field=models.CharField(blank=True, help_text='Original procedure code before grouping', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patientrecords',
            name='procedure_count_total',
            field=models.IntegerField(blank=True, help_text='Total number of procedures', null=True),
        ),
        migrations.AddField(
            model_name='patientrecords',
            name='procedures',
            field=models.JSONField(blank=True, help_text='JSON array of procedures for grouped CPT records', null=True),
        ),
        migrations.AddField(
            model_name='patientrecords',
            name='total_amount_all_procedures',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Sum of all procedure amounts', max_digits=10, null=True),
        ),
    ]
