# Generated by Django 5.1.4 on 2025-08-09 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0021_patientrecords_is_grouped_cpt_record_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientrecords',
            name='is_grouped_cpt_record',
        ),
        migrations.RemoveField(
            model_name='patientrecords',
            name='original_procedure_code',
        ),
        migrations.RemoveField(
            model_name='patientrecords',
            name='procedure_count_total',
        ),
        migrations.RemoveField(
            model_name='patientrecords',
            name='procedures',
        ),
        migrations.RemoveField(
            model_name='patientrecords',
            name='total_amount_all_procedures',
        ),
    ]
