# Generated by Django 5.1.4 on 2025-08-09 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0022_remove_patientrecords_is_grouped_cpt_record_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecords',
            name='cpt_procedures',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='patientrecords',
            name='is_cpt_grouped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientrecords',
            name='procedure_count_total',
            field=models.IntegerField(default=1),
        ),
    ]
