# Generated by Django 5.1.4 on 2025-08-13 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0023_patientrecords_cpt_procedures_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_name', models.CharField(max_length=255)),
                ('phone_no', models.CharField(max_length=20)),
                ('extension', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.TextField()),
                ('open_close_time', models.CharField(max_length=50)),
                ('prefix', models.CharField(max_length=10)),
                ('claim_address', models.TextField()),
                ('appeal_address', models.TextField()),
                ('claim_tfl_days', models.IntegerField()),
                ('appeal_tfl_days', models.IntegerField()),
                ('web_page_address', models.URLField(blank=True, null=True)),
                ('group_username', models.CharField(max_length=100)),
                ('group_password', models.CharField(max_length=100)),
                ('individual_username', models.CharField(max_length=100)),
                ('individual_password', models.CharField(max_length=100)),
                ('password_expiry_duration', models.IntegerField(help_text='Duration in days')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_records_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_records_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'insurance_records',
                'ordering': ['-created_at'],
            },
        ),
    ]
