# Generated by Django 5.1.4 on 2025-08-13 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0024_insurancerecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InsuranceRecord',
        ),
    ]
