# Generated by Django 5.1.4 on 2025-08-13 03:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0025_delete_insurancerecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=50, null=True)),
                ('extension', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('open_close_time', models.CharField(blank=True, max_length=100, null=True)),
                ('prefix', models.CharField(blank=True, max_length=50, null=True)),
                ('claim_address', models.TextField(blank=True, null=True)),
                ('appeal_address', models.TextField(blank=True, null=True)),
                ('claim_tfl_days', models.IntegerField(blank=True, help_text='Claim TFL (days)', null=True)),
                ('appeal_tfl_days', models.IntegerField(blank=True, help_text='Appeal TFL (days)', null=True)),
                ('web_page_address', models.URLField(blank=True, null=True)),
                ('group_username', models.CharField(blank=True, max_length=255, null=True)),
                ('group_password', models.CharField(blank=True, max_length=255, null=True)),
                ('individual_username', models.CharField(blank=True, max_length=255, null=True)),
                ('individual_password', models.CharField(blank=True, max_length=255, null=True)),
                ('password_expiry_duration', models.IntegerField(blank=True, help_text='Password expiry duration in days', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_insurances', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_insurances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'insurance',
                'ordering': ['-created_at'],
            },
        ),
    ]
