# Generated by Django 5.1.4 on 2025-08-13 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0026_insurance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Insurance',
        ),
    ]
