# Generated by Django 5.1.4 on 2025-08-13 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0027_delete_insurance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_name', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=50, null=True)),
                ('extension', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('open_close_time', models.CharField(blank=True, max_length=100, null=True)),
                ('prefix', models.CharField(blank=True, max_length=10, null=True)),
                ('claim_address', models.TextField(blank=True, null=True)),
                ('appeal_address', models.TextField(blank=True, null=True)),
                ('claim_tfl', models.IntegerField(blank=True, help_text='Claim TFL in days', null=True)),
                ('appeal_tfl', models.IntegerField(blank=True, help_text='Appeal TFL in days', null=True)),
                ('web_page_address', models.URLField(blank=True, null=True)),
                ('group_username', models.CharField(blank=True, max_length=100, null=True)),
                ('group_password', models.CharField(blank=True, max_length=100, null=True)),
                ('individual_username', models.CharField(blank=True, max_length=100, null=True)),
                ('individual_password', models.CharField(blank=True, max_length=100, null=True)),
                ('password_expiry_duration', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'insurance',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TableField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(max_length=100, unique=True)),
                ('field_label', models.CharField(max_length=200)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('password', 'Password'), ('email', 'Email'), ('tel', 'Phone')], default='text', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'table_fields',
                'ordering': ['id'],
            },
        ),
    ]
