# Generated by Django 5.1.4 on 2025-08-13 07:14

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0028_insurance_tablefield'),
        ('setups', '0036_billingsystemmappingrecord_is_cpt_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalInsuranceInformation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('insurance_name', models.CharField(max_length=255)),
                ('phone_no', models.CharField(blank=True, max_length=50, null=True)),
                ('extension', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('open_close_time', models.CharField(blank=True, max_length=100, null=True)),
                ('prefix', models.CharField(blank=True, max_length=50, null=True)),
                ('claim_address', models.TextField(blank=True, null=True)),
                ('appeal_address', models.TextField(blank=True, null=True)),
                ('claim_tfl_days', models.IntegerField(default=0, help_text='Claim Time Filing Limit in days')),
                ('appeal_tfl_days', models.IntegerField(default=0, help_text='Appeal Time Filing Limit in days')),
                ('web_page_address', models.URLField(blank=True, null=True)),
                ('group_username', models.CharField(blank=True, max_length=255, null=True)),
                ('group_password', models.CharField(blank=True, max_length=255, null=True)),
                ('individual_username', models.CharField(blank=True, max_length=255, null=True)),
                ('individual_password', models.CharField(blank=True, max_length=255, null=True)),
                ('password_expiry_duration', models.IntegerField(default=90, help_text='Password expiry duration in days')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='setups.projects')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical insurance information',
                'verbose_name_plural': 'historical insurance informations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='InsuranceInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('insurance_name', models.CharField(max_length=255)),
                ('phone_no', models.CharField(blank=True, max_length=50, null=True)),
                ('extension', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('open_close_time', models.CharField(blank=True, max_length=100, null=True)),
                ('prefix', models.CharField(blank=True, max_length=50, null=True)),
                ('claim_address', models.TextField(blank=True, null=True)),
                ('appeal_address', models.TextField(blank=True, null=True)),
                ('claim_tfl_days', models.IntegerField(default=0, help_text='Claim Time Filing Limit in days')),
                ('appeal_tfl_days', models.IntegerField(default=0, help_text='Appeal Time Filing Limit in days')),
                ('web_page_address', models.URLField(blank=True, null=True)),
                ('group_username', models.CharField(blank=True, max_length=255, null=True)),
                ('group_password', models.CharField(blank=True, max_length=255, null=True)),
                ('individual_username', models.CharField(blank=True, max_length=255, null=True)),
                ('individual_password', models.CharField(blank=True, max_length=255, null=True)),
                ('password_expiry_duration', models.IntegerField(default=90, help_text='Password expiry duration in days')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_insurance_info', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_information', to='setups.projects')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_insurance_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'insurance_information',
                'unique_together': {('insurance_name', 'project')},
            },
        ),
        migrations.DeleteModel(
            name='Insurance',
        ),
        migrations.DeleteModel(
            name='TableField',
        ),
    ]
