# Generated by Django 5.1.4 on 2025-08-13 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0029_historicalinsuranceinformation_insuranceinformation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='insuranceinformation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='insuranceinformation',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='insuranceinformation',
            name='appeal_tfl_days',
            field=models.IntegerField(blank=True, help_text='Appeal TFL (days)', null=True),
        ),
        migrations.AlterField(
            model_name='insuranceinformation',
            name='claim_tfl_days',
            field=models.IntegerField(blank=True, help_text='Claim TFL (days)', null=True),
        ),
        migrations.AlterField(
            model_name='insuranceinformation',
            name='created_by',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_insurance_info', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='insuranceinformation',
            name='extension',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='insuranceinformation',
            name='group_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='insuranceinformation',
            name='group_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='insuranceinformation',
            name='individual_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='insuranceinformation',
            name='individual_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='insuranceinformation',
            name='password_expiry_duration',
            field=models.IntegerField(blank=True, help_text='Password expiry duration in days', null=True),
        ),
        migrations.AlterField(
            model_name='insuranceinformation',
            name='phone_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='insuranceinformation',
            name='prefix',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='insuranceinformation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_info', to='records.projectpage'),
        ),
        migrations.DeleteModel(
            name='HistoricalInsuranceInformation',
        ),
        migrations.RemoveField(
            model_name='insuranceinformation',
            name='updated_by',
        ),
    ]
