# Generated by Django 5.1.4 on 2025-08-13 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0030_project_alter_insuranceinformation_options_and_more'),
        ('setups', '0036_billingsystemmappingrecord_is_cpt_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.AlterField(
            model_name='insuranceinformation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_insurance_info', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='insuranceinformation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_info', to='setups.projects'),
        ),
    ]
