# Generated by Django 5.1.4 on 2025-08-14 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0031_delete_project_alter_insuranceinformation_created_by_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InsuranceInformation',
        ),
    ]
