# Generated by Django 5.1.4 on 2025-08-14 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0032_delete_insuranceinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('field_type', models.CharField(max_length=50)),
                ('is_required', models.BooleanField(default=False)),
                ('max_length', models.IntegerField(blank=True, null=True)),
                ('default_value', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkFlowHeadersWithDynamic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dynamic_fields', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
