# Generated by Django 5.1.4 on 2025-08-14 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0033_dynamicfield_workflowheaderswithdynamic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DynamicField',
        ),
        migrations.DeleteModel(
            name='WorkFlowHeadersWithDynamic',
        ),
    ]
