# Generated by Django 5.1.4 on 2025-08-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0035_workflowheaderfield_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkFlowHeaderField',
        ),
        migrations.RemoveField(
            model_name='workflowheaders',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='workflowheaders',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='workflowheaders',
            name='additional_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflowheaders',
            name='allowed_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='workflowheaders',
            name='call_reference',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='workflowheaders',
            name='check_mailing_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='workflowheaders',
            name='check_number',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='workflowheaders',
            name='claim_number',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='workflowheaders',
            name='clearing_house_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='workflowheaders',
            name='clearing_house_name',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='workflowheaders',
            name='coinsurance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='workflowheaders',
            name='copayment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='workflowheaders',
            name='deductible_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='workflowheaders',
            name='encashment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflowheaders',
            name='eob_available_on_website',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workflowheaders',
            name='fax',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflowheaders',
            name='fax_provided',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workflowheaders',
            name='insurance_name',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='workflowheaders',
            name='insurance_phone',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='workflowheaders',
            name='is_check_cashed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workflowheaders',
            name='is_check_paid_on_correct_address',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workflowheaders',
            name='is_paid_date_crossed_45_days',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workflowheaders',
            name='is_payment_cleared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workflowheaders',
            name='is_single_bulk_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workflowheaders',
            name='mailing_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflowheaders',
            name='mode_of_payment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='workflowheaders',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='workflowheaders',
            name='paid_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflowheaders',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='workflowheaders',
            name='processed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflowheaders',
            name='reason_for_not_reissuing_new_payment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflowheaders',
            name='reason_for_not_sending_request_for_check_tracer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflowheaders',
            name='rep_agrees_to_reissue_new_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workflowheaders',
            name='rep_agrees_to_reissue_new_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workflowheaders',
            name='rep_agrees_to_run_check_tracer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workflowheaders',
            name='rep_name',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='workflowheaders',
            name='source_of_status',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='workflowheaders',
            name='source_to_get_eob',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='workflowheaders',
            name='tat_for_check_tracer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workflowheaders',
            name='tat_for_encashment_of_payment',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workflowheaders',
            name='tat_to_receive_new_payment',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workflowheaders',
            name='transaction_id',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='workflowheaders',
            name='w9_form_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workflowheaders',
            name='website_name',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='workflowheaders',
            name='website_name_link',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterModelTable(
            name='workflowheaders',
            table=None,
        ),
    ]
