# Generated by Django 5.1.4 on 2025-08-14 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0036_delete_workflowheaderfield_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codes',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_project', to='records.projectpage'),
        ),
    ]
