# Generated by Django 5.1.4 on 2025-08-18 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0037_alter_codes_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codes',
            options={'managed': False},
        ),
    ]
