# Generated by Django 5.1.4 on 2025-08-18 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0038_alter_codes_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codes',
            options={},
        ),
    ]
