# Generated by Django 5.1.4 on 2025-08-18 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0040_alter_codes_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codes',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_project', to='records.projectpage'),
        ),
    ]
