# Generated by Django 5.1.4 on 2025-08-19 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0043_historicaltargetcorrection_targetcorrection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='targetcorrection',
            options={'ordering': ['-id'], 'verbose_name': 'Target Correction', 'verbose_name_plural': 'Target Corrections'},
        ),
        migrations.RemoveField(
            model_name='targetcorrection',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='targetcorrection',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='targetcorrection',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='targetcorrection',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='HistoricalTargetCorrection',
        ),
    ]
