# Generated by Django 5.1.4 on 2025-08-19 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0044_alter_targetcorrection_options_and_more'),
        ('setups', '0038_alter_historicalroles_screens_alter_roles_screens'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='targetcorrection',
            options={'ordering': ['-created_at'], 'verbose_name': 'Target Correction', 'verbose_name_plural': 'Target Corrections'},
        ),
        migrations.AddField(
            model_name='targetcorrection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='targetcorrection',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_corrections_created', to='setups.usercredentialssetup'),
        ),
        migrations.AddField(
            model_name='targetcorrection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
