# Generated by Django 5.1.4 on 2025-08-23 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0045_alter_targetcorrection_options_and_more'),
        ('setups', '0039_alter_historicalroles_screens_alter_roles_screens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codes',
            name='status_code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='codes',
            unique_together={('status_code', 'project')},
        ),
    ]
