# Generated by Django 5.2.5 on 2025-08-30 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0047_customheader'),
        ('setups', '0039_alter_historicalroles_screens_alter_roles_screens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customheader',
            name='project_id',
        ),
        migrations.AddField(
            model_name='customheader',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setups.projects'),
        ),
    ]
