# Generated by Django 5.2.5 on 2025-08-30 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0048_remove_customheader_project_id_customheader_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomHeader',
        ),
    ]
