# Generated by Django 5.2.5 on 2025-09-11 11:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0049_delete_customheader'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TabTiming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_key', models.CharField(help_text='Unique identifier for the tab', max_length=255)),
                ('patient_id', models.CharField(blank=True, help_text='Patient ID if applicable', max_length=100, null=True)),
                ('tab_name', models.CharField(help_text='Display name of the tab', max_length=255)),
                ('sub_header', models.CharField(help_text='Sub header section', max_length=100)),
                ('tab_type', models.CharField(help_text="Type of tab (e.g., 'demographics', 'insurance')", max_length=100)),
                ('project_id', models.CharField(help_text='Associated project ID', max_length=100)),
                ('opened_at', models.DateTimeField(help_text='When the tab was opened')),
                ('closed_at', models.DateTimeField(blank=True, help_text='When the tab was closed', null=True)),
                ('total_active_time', models.IntegerField(default=0, help_text='Total active time in milliseconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tab_timings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'records_tab_timing',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'tab_type', 'created_at'], name='records_tab_user_id_c99c3c_idx'), models.Index(fields=['patient_id', 'user'], name='records_tab_patient_751c7b_idx'), models.Index(fields=['project_id', 'created_at'], name='records_tab_project_76356e_idx'), models.Index(fields=['tab_key'], name='records_tab_tab_key_746b0c_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserTabActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('project_id', models.CharField(max_length=100)),
                ('tab_type', models.CharField(max_length=100)),
                ('sub_header', models.CharField(max_length=100)),
                ('total_tabs_opened', models.IntegerField(default=0)),
                ('total_active_time', models.IntegerField(default=0, help_text='Total active time in milliseconds')),
                ('unique_patients_viewed', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'records_user_tab_activity',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', 'date'], name='records_use_user_id_1d0357_idx'), models.Index(fields=['project_id', 'date'], name='records_use_project_ace6fc_idx'), models.Index(fields=['date'], name='records_use_date_2e9517_idx')],
                'unique_together': {('user', 'date', 'project_id', 'tab_type', 'sub_header')},
            },
        ),
    ]
