# Generated by Django 5.2.5 on 2025-09-11 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0050_tabtiming_usertabactivity'),
        ('setups', '0039_alter_historicalroles_screens_alter_roles_screens'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tabtiming',
            name='records_tab_project_76356e_idx',
        ),
        migrations.RemoveIndex(
            model_name='usertabactivity',
            name='records_use_project_ace6fc_idx',
        ),
        migrations.RemoveField(
            model_name='tabtiming',
            name='project_id',
        ),
        migrations.AlterUniqueTogether(
            name='usertabactivity',
            unique_together={('user', 'date', 'project', 'tab_type', 'sub_header')},
        ),
        migrations.AddField(
            model_name='tabtiming',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Associated project', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tab_timings', to='setups.projects'),
        ),
        migrations.AddField(
            model_name='usertabactivity',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Associated project', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_activities', to='setups.projects'),
        ),
        migrations.AddIndex(
            model_name='tabtiming',
            index=models.Index(fields=['project', 'created_at'], name='records_tab_project_76356e_idx'),
        ),
        migrations.AddIndex(
            model_name='usertabactivity',
            index=models.Index(fields=['project', 'date'], name='records_use_project_ace6fc_idx'),
        ),
        migrations.RemoveField(
            model_name='usertabactivity',
            name='project_id',
        ),
    ]
