# Generated by Django 5.2.5 on 2025-09-11 11:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0051_remove_tabtiming_records_tab_project_76356e_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tabtiming',
            name='records_tab_project_76356e_idx',
        ),
        migrations.RemoveIndex(
            model_name='usertabactivity',
            name='records_use_project_ace6fc_idx',
        ),
        migrations.RemoveField(
            model_name='tabtiming',
            name='project',
        ),
        migrations.AlterUniqueTogether(
            name='usertabactivity',
            unique_together={('user', 'date', 'project_id', 'tab_type', 'sub_header')},
        ),
        migrations.AddField(
            model_name='tabtiming',
            name='project_id',
            field=models.CharField(blank=True, help_text='Associated project ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usertabactivity',
            name='project_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='tabtiming',
            index=models.Index(fields=['project_id', 'created_at'], name='records_tab_project_76356e_idx'),
        ),
        migrations.AddIndex(
            model_name='usertabactivity',
            index=models.Index(fields=['project_id', 'date'], name='records_use_project_ace6fc_idx'),
        ),
        migrations.RemoveField(
            model_name='usertabactivity',
            name='project',
        ),
    ]
