# Generated by Django 5.1.4 on 2025-05-02 01:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rules', '0001_initial'),
        ('setups', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrulesandtypes',
            name='approved_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='setups.usercredentialssetup'),
        ),
        migrations.AddField(
            model_name='historicalrulesandtypes',
            name='approves_1',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='setups.usercredentialssetup'),
        ),
        migrations.AddField(
            model_name='historicalrulesandtypes',
            name='approves_2',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='setups.usercredentialssetup'),
        ),
        migrations.AddField(
            model_name='historicalrulesandtypes',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='historicalrulesandtypes',
            name='department',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='setups.departments'),
        ),
        migrations.AddField(
            model_name='historicalrulesandtypes',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalrulesandtypes',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AddField(
            model_name='ruleactions',
            name='custom_bins',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rule_action_custom_bin_set', to='setups.custombins'),
        ),
        migrations.AddField(
            model_name='ruleactions',
            name='reviewing_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalrulesandtypes',
            name='action',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='rules.ruleactions'),
        ),
        migrations.AddField(
            model_name='rulesandtypes',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_actions', to='rules.ruleactions'),
        ),
        migrations.AddField(
            model_name='rulesandtypes',
            name='approved_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules_approved_by_set', to='setups.usercredentialssetup'),
        ),
        migrations.AddField(
            model_name='rulesandtypes',
            name='approves_1',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules_approve_1_set', to='setups.usercredentialssetup'),
        ),
        migrations.AddField(
            model_name='rulesandtypes',
            name='approves_2',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules_approve_2_set', to='setups.usercredentialssetup'),
        ),
        migrations.AddField(
            model_name='rulesandtypes',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='rulesandtypes',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setups.departments'),
        ),
        migrations.AddField(
            model_name='rulesandtypes',
            name='project',
            field=models.ManyToManyField(related_name='rules_project_set', to='setups.projects'),
        ),
        migrations.AddField(
            model_name='rulesandtypes',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
    ]
