# Generated by Django 5.1.4 on 2025-08-05 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0002_initial'),
        ('setups', '0019_remove_billingsystemmappingrecord_projects_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rulesandtypes',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules_approved_by_set', to='setups.usercredentialssetup'),
        ),
        migrations.AlterField(
            model_name='rulesandtypes',
            name='approves_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules_approve_1_set', to='setups.usercredentialssetup'),
        ),
        migrations.AlterField(
            model_name='rulesandtypes',
            name='approves_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules_approve_2_set', to='setups.usercredentialssetup'),
        ),
    ]
